-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , SUM(purchase_amount) as revenue 
FROM customers
GROUP BY gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount ?
SELECT customer_id , purchase_amount 
from customers
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers);

-- Q3. Which are the top five products with the highest average review rating ?
select item_purchased ,avg(review_rating) as Avg_rating
from customers 
group by item_purchased 
order by avg(review_rating) desc 
limit 5 ;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shippihg.
select shipping_type, round(avg(purchase_amount),2) as avg_price
from customers
where shipping_type in ('Standard','Express')
group by shipping_type ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spending , round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status ;

-- Q6. Which five products have the highest percentage of purchases with discounts applied ?
select item_purchased , round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customers 
group by item_purchased
order by discount_rate desc 
limit 5 ;

-- Q7. Segment customers into New, Returning, and Loyal based on their total of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id , previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases  between 2 and 10 then 'Returning'
when previous_purchases > 10 then 'Loyal'
end as customer_segment from customers
)
select customer_segment,count(*) from customer_type
group by customer_segment ;

-- Q8. What are the top 3 most purchased products within each category ?
with category_item as (select category , item_purchased , count(customer_id) as total_quantity,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank from customers
group by category,item_purchased)
select item_rank,category , item_purchased ,  total_quantity from category_item 
having item_rank <= 3;

-- Q9. Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
select subscription_status , count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5  
group by subscription_status ;

-- Q10. What is the revenue contribution of each age group ?
select age_group ,sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc ;